import deadImagePaths from './generated/dead-description-images.json';

/**
 * Cleans Shopify rich-text HTML (collection descriptions, blog article bodies)
 * before it is rendered with dangerouslySetInnerHTML.
 *
 * Shopify embeds raw <img src="cdn.shopify.com/..."> tags in this HTML, which
 * bypass next/image. Two problems result, both handled here:
 *
 *  1. Oversized images. Shopify serves the full original (often 1365px+ wide) into
 *     a column that is at most ~896px (max-w-4xl). We append the Shopify CDN
 *     `width` transform param so the CDN serves a right-sized image instead.
 *  2. Dead images. Some embedded files were deleted from the CDN and now 404,
 *     showing a broken-image icon. We strip those <img> tags entirely. The dead
 *     list is generated by scripts/check-description-images.mjs (re-run before a
 *     deploy, or after Ting re-uploads images, to refresh it).
 *  3. Embedded <h1> headings. Shopify SEO content often opens with its own <h1>,
 *     which competes with the page-title <h1> (two h1s per page). We demote every
 *     embedded h1 to h2 so the page keeps a single, correct top-level heading.
 */

const SHOPIFY_CDN_HOST = 'cdn.shopify.com';

/** The shop's numeric Files path on cdn.shopify.com (constant for this store). */
const SHOPIFY_FILES_PREFIX = '/s/files/1/0797/0819/3023/';
const MIOZUKI_CDN_HOST = /^(www\.)?miozuki\.co\.nz$/i;

/**
 * Pin an embedded image URL to cdn.shopify.com.
 *
 * Shopify embeds images on the shop's PRIMARY domain
 * (miozuki.co.nz/cdn/shop/files/...). After the cutover that domain is Vercel and
 * /cdn/shop 404s, so every embedded image breaks, including any Ting re-uploads,
 * since Shopify keeps embedding them on the primary domain. cdn.shopify.com serves
 * the same asset at /s/files/<shop>/files/... regardless of the shop domain, so
 * rewrite host + path to it. Already-cdn and non-Shopify URLs are returned as-is.
 */
function normalizeCdnSrc(src: string): string {
  try {
    const url = new URL(src);
    if (MIOZUKI_CDN_HOST.test(url.hostname) && url.pathname.startsWith('/cdn/shop/')) {
      url.protocol = 'https:';
      url.hostname = SHOPIFY_CDN_HOST;
      url.pathname = url.pathname.replace('/cdn/shop/', SHOPIFY_FILES_PREFIX);
      return url.toString();
    }
    return src;
  } catch {
    return src;
  }
}

/**
 * Render width for embedded Shopify CDN images. The description/article column is
 * max-w-4xl (~896px); 1024 keeps quality on higher-density screens while trimming
 * oversized originals well below their full size.
 */
const DEFAULT_IMG_WIDTH = 1024;

const DEAD_IMAGE_PATHS = new Set<string>(deadImagePaths as string[]);

const IMG_TAG = /<img\b[^>]*>/gi;
const SRC_ATTR = /\bsrc="([^"]*)"/i;
const EMPTY_PARAGRAPH = /<p>(?:\s|&nbsp;)*<\/p>/gi;
const H1_OPEN = /<h1(\s[^>]*)?>/gi;
const H1_CLOSE = /<\/h1>/gi;

function isShopifyCdn(src: string): boolean {
  try {
    return new URL(src).hostname === SHOPIFY_CDN_HOST;
  } catch {
    return false;
  }
}

function pathOf(src: string): string | null {
  try {
    return new URL(src).pathname;
  } catch {
    return null;
  }
}

/** Add a `width` transform param to a Shopify CDN image URL if not already present. */
function withWidth(src: string, width: number): string {
  try {
    const url = new URL(src);
    if (!url.searchParams.has('width')) url.searchParams.set('width', String(width));
    return url.toString();
  } catch {
    return src;
  }
}

/** Set (override) the `width` transform param, for srcset candidate URLs. */
function setWidth(src: string, width: number): string {
  try {
    const url = new URL(src);
    url.searchParams.set('width', String(width));
    return url.toString();
  } catch {
    return src;
  }
}

/**
 * Widths for the embedded-image srcset. The column displays at ~360px on phones
 * and up to ~848px on desktop; these cover 1x-2x density without shipping the
 * oversized originals Shopify embeds (Lighthouse flagged ~84 KiB wasted per image).
 */
const SRCSET_WIDTHS = [480, 768, 1024];
const IMG_SIZES = '(max-width: 927px) 100vw, 896px';

export function cleanDescriptionHtml(
  html: string | null | undefined,
  width: number = DEFAULT_IMG_WIDTH,
): string {
  if (!html) return '';
  let imgIndex = 0;
  const cleaned = html.replace(IMG_TAG, (tag) => {
    const match = tag.match(SRC_ATTR);
    if (!match) return tag;
    // Pin primary-domain /cdn/shop URLs to cdn.shopify.com so they survive cutover.
    const src = normalizeCdnSrc(match[1]);
    if (!isShopifyCdn(src)) return src === match[1] ? tag : tag.replace(SRC_ATTR, `src="${src}"`);
    const path = pathOf(src);
    if (path && DEAD_IMAGE_PATHS.has(path)) return ''; // strip dead image
    const isFirstImage = imgIndex === 0;
    imgIndex += 1;
    // Responsive candidates so phones stop downloading the desktop-width file.
    let attrs = '';
    if (!/\bsrcset=/i.test(tag)) {
      const srcset = SRCSET_WIDTHS.map((w) => `${setWidth(src, w)} ${w}w`).join(', ');
      attrs += ` srcset="${srcset}" sizes="${IMG_SIZES}"`;
    }
    // Lazy-load everything except the first embedded image, which on some blog
    // articles sits above the fold and can be the LCP element.
    if (!isFirstImage && !/\bloading=/i.test(tag)) attrs += ' loading="lazy"';
    if (!/\bdecoding=/i.test(tag)) attrs += ' decoding="async"';
    return tag.replace(SRC_ATTR, `src="${withWidth(src, width)}"${attrs}`);
  });
  // Demote embedded h1s to h2 so they do not compete with the page-title h1.
  const demoted = cleaned.replace(H1_OPEN, '<h2$1>').replace(H1_CLOSE, '</h2>');
  // Stripping an image can leave an empty wrapper paragraph; drop those.
  return demoted.replace(EMPTY_PARAGRAPH, '');
}
