import deadImagePaths from './generated/dead-description-images.json';

/**
 * Cleans Shopify rich-text HTML (collection descriptions, blog article bodies)
 * before it is rendered with dangerouslySetInnerHTML.
 *
 * Shopify embeds raw <img src="cdn.shopify.com/..."> tags in this HTML, which
 * bypass next/image. Two problems result, both handled here:
 *
 *  1. Oversized images. Shopify serves the full original (often 1365px+ wide) into
 *     a column that is at most ~896px (max-w-4xl). We append the Shopify CDN
 *     `width` transform param so the CDN serves a right-sized image instead.
 *  2. Dead images. Some embedded files were deleted from the CDN and now 404,
 *     showing a broken-image icon. We strip those <img> tags entirely. The dead
 *     list is generated by scripts/check-description-images.mjs (re-run before a
 *     deploy, or after Ting re-uploads images, to refresh it).
 */

const SHOPIFY_CDN_HOST = 'cdn.shopify.com';

/**
 * Render width for embedded Shopify CDN images. The description/article column is
 * max-w-4xl (~896px); 1024 keeps quality on higher-density screens while trimming
 * oversized originals well below their full size.
 */
const DEFAULT_IMG_WIDTH = 1024;

const DEAD_IMAGE_PATHS = new Set<string>(deadImagePaths as string[]);

const IMG_TAG = /<img\b[^>]*>/gi;
const SRC_ATTR = /\bsrc="([^"]*)"/i;
const EMPTY_PARAGRAPH = /<p>(?:\s|&nbsp;)*<\/p>/gi;

function isShopifyCdn(src: string): boolean {
  try {
    return new URL(src).hostname === SHOPIFY_CDN_HOST;
  } catch {
    return false;
  }
}

function pathOf(src: string): string | null {
  try {
    return new URL(src).pathname;
  } catch {
    return null;
  }
}

/** Add a `width` transform param to a Shopify CDN image URL if not already present. */
function withWidth(src: string, width: number): string {
  try {
    const url = new URL(src);
    if (!url.searchParams.has('width')) url.searchParams.set('width', String(width));
    return url.toString();
  } catch {
    return src;
  }
}

export function cleanDescriptionHtml(
  html: string | null | undefined,
  width: number = DEFAULT_IMG_WIDTH,
): string {
  if (!html) return '';
  const cleaned = html.replace(IMG_TAG, (tag) => {
    const match = tag.match(SRC_ATTR);
    if (!match) return tag;
    const src = match[1];
    if (!isShopifyCdn(src)) return tag;
    const path = pathOf(src);
    if (path && DEAD_IMAGE_PATHS.has(path)) return ''; // strip dead image
    return tag.replace(SRC_ATTR, `src="${withWidth(src, width)}"`);
  });
  // Stripping an image can leave an empty wrapper paragraph; drop those.
  return cleaned.replace(EMPTY_PARAGRAPH, '');
}
